from game.world import WORLD_DIMENSION

# Blue, Red, Green, Amber @ Material Palette
COLOR_PLAYERS = [(33, 150, 243), (244, 67, 54), (76, 175, 80), (255, 193, 7)]
COLOR_BACKGROUND = (250, 250, 250)
COLOR_BACKGROUND_SECONDARY = (224, 224, 224)

DISPLAY_RESOLUTION = (1600, 900)  # type: (int, int)

TILE_SIZE = min(DISPLAY_RESOLUTION[0] / float(WORLD_DIMENSION[0]),
                DISPLAY_RESOLUTION[1] / float(WORLD_DIMENSION[1]))
SUB_SURFACE_SIZE = (TILE_SIZE * WORLD_DIMENSION[0],
                    TILE_SIZE * WORLD_DIMENSION[1])
SUB_SURFACE_BORDER = ((DISPLAY_RESOLUTION[0] - SUB_SURFACE_SIZE[0]) / 2,
                      (DISPLAY_RESOLUTION[1] - SUB_SURFACE_SIZE[1]) / 2)
